version: '3'
services:
  nginx:
    build: .
    privileged: true
    restart: always
    networks:
      - qytang_network
    ports:
#      - 80:80
      - 443:443

networks:
  qytang_network:
    driver: bridge
